/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdsenseRouteImport } from './routes/adsense'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'
import { Route as GroupSlugRouteImport } from './routes/group.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsenseRoute = AdsenseRouteImport.update({
  id: '/adsense',
  path: '/adsense',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSlugRoute = GroupSlugRouteImport.update({
  id: '/group/$slug',
  path: '/group/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adsense': typeof AdsenseRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/group/$slug': typeof GroupSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adsense': typeof AdsenseRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/group/$slug': typeof GroupSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adsense': typeof AdsenseRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/group/$slug': typeof GroupSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adsense'
    | '/categories'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/group/$slug'
    | '/quiz/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adsense'
    | '/categories'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/group/$slug'
    | '/quiz/$slug'
  id:
    | '__root__'
    | '/'
    | '/adsense'
    | '/categories'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/group/$slug'
    | '/quiz/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsenseRoute: typeof AdsenseRoute
  CategoriesRoute: typeof CategoriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GroupSlugRoute: typeof GroupSlugRoute
  QuizSlugRoute: typeof QuizSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adsense': {
      id: '/adsense'
      path: '/adsense'
      fullPath: '/adsense'
      preLoaderRoute: typeof AdsenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$slug': {
      id: '/group/$slug'
      path: '/group/$slug'
      fullPath: '/group/$slug'
      preLoaderRoute: typeof GroupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsenseRoute: AdsenseRoute,
  CategoriesRoute: CategoriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  GroupSlugRoute: GroupSlugRoute,
  QuizSlugRoute: QuizSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
